# Generated by Django 6.0.2 on 2026-02-04 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='user_id',
            new_name='creator',
        ),
    ]
