# Generated by Django 6.0.2 on 2026-02-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0002_rename_user_id_ad_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='creator',
            new_name='سازنده',
        ),
    ]
