# Generated by Django 6.0.2 on 2026-02-04 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0003_rename_creator_ad_سازنده'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='سازنده',
            new_name='Creator',
        ),
    ]
