# Generated by Django 6.0.2 on 2026-02-04 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ads', '0004_rename_سازنده_ad_creator'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ad',
            old_name='Creator',
            new_name='creator',
        ),
    ]
